### ISSUE TITLE
Page Editor - Image size change upon dragging

### ISSUE THREAD

**Issue by Lule-M** [ElStefanos/Advanced-Web-Tools#51]
Upon dragging an image which has it's height and width properties changed, it's height seems to expand, and it also appears to zoom in.

**Comment by ElStefanos** [comment]
Rough fix was implemented with CSS. Image will now have 50% width and auto height when being dragged. Further testing is needed since larger images may break the size of the block.

**Comment by Lule-M** [comment]
Issue partially fixed for the most part. With certain images, upon clicking them and dragging, they take up much more space below them than other elements or images do.

**Comment by ElStefanos** [comment]
After tests, it seems that the issue is fixed. If it occurs again, please open a new ticket and reference to this issue.
